version: '2'
services:
  db:
    image: vonji/db
    build: ./database
    container_name: db
    ports:
     - "5432:5432"
  api:
    image: vonji/api
    build: ./api
    container_name: api
    ports:
     - "1618:1618"
    depends_on:
     - db
    restart: unless-stopped
    links:
     - db
  client:
    image: vonji/app
    build: ./client
    container_name: client
    ports:
     - "8080:8080"
    depends_on:
     - api
