version: '2'
services:
  db:
    image: postgres:9.6
    build: ./database
    ports:
     - "5432:5432"
    expose:
     VIRTUAL_HOST: app.vonji.fr
  api:
    image: golang:1-6
    build: ./api
    ports:
     - "1618:1618"
    depends_on:
     - db
    restart: unless-stopped
    expose:
     VIRTUAL_HOST: app.vonji.fr 
  client:
    image: node:latest
    build: ./client
    ports:
     - "54678:8080"
    expose:
     - "8080"
    depends_on:
     - api
    expose:
     VIRTUAL_HOST: app.vonji.fr
 
