ALTER SEQUENCE requests_id_seq RESTART WITH 1;
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-23T7:46:23+02:00','2016-5-23T7:46:23+02:00',NULL,'26','Ayant un lumbago depuis plusieurs semaines, j''ai besoin d''aide pour passer la tondeuse dans mon jardin. Il s''agit d''un jardin de 15m x 15m, quand je suis en forme, ça me prend 2h max','Passer la tondeuse','12','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-8T17:19:16+02:00','2016-7-8T17:19:16+02:00',NULL,'30','Je suis envahie par les mauvaises herbes, elles ont une hauteur de environ 80 cm. Je ne possède pas le métériel suffisant pour les raser, je n''ai qu''une simple cisaille','Raser des mauvaises herbes','1','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-17T15:36:56+02:00','2016-7-17T15:36:56+02:00',NULL,'31','J''aurai besoin d''un coup de main pour m''aider à planter un pin. ','Planter un pin','5','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-11T1:10:23+02:00','2016-6-11T1:10:23+02:00',NULL,'68','Habitant au rez-de-chaussée, il y a un arbuste juste devant ma fenêtre, est ce quelqu''un pourrait m''aider pour l''élaguer?','Elaguer un arbuste','3','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-9T13:17:25+02:00','2016-5-9T13:17:25+02:00',NULL,'38','Adepte de bons légumes, je voudrais des conseils et de l''accompagnement pour planter un potager, je voudrais commencer par des tomates. Mais je ne sais quelle graine prendre et surtout si l''espace que j''ai aménager dans mon jardin est propice à ce type de plantation','Planter un potager','11','true', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-15T4:47:21+02:00','2016-5-15T4:47:21+02:00',NULL,'36','J''ai de très beaux rosiers sur ma terasse, mais je cherche quelqu''un qui pourrait me montrer la bonne méthode pour les tailler correctement','Tailler un rosier','7','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-17T4:21:45+02:00','2016-7-17T4:21:45+02:00',NULL,'13','J''ai besoin d''aide pour récolter des oranges et des citrons dans ma maison de campagne.','Récolter','4','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-5T2:56:3+02:00','2016-5-5T2:56:3+02:00',NULL,'68','j''ai besoin d''aide et de conseils pour semer du gazon ','Semer','12','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-4T18:8:49+02:00','2016-5-4T18:8:49+02:00',NULL,'3','Je cherche une personne pour faire l''arrosage de mon jardin pendant mes congés','Arroser','10','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-27T5:6:19+02:00','2016-7-27T5:6:19+02:00',NULL,'59','Je recherche une personne de confiance pour garder mes enfants mercredi prochain','garde mes 2 enfants','6','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-8T11:6:38+02:00','2016-6-8T11:6:38+02:00',NULL,'65','Etant très stressé en ce moment à cause du boulot, je recherche une personne qui sache faire des massages pour me détendre le dos','Me faire masser le dos','7','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-3T12:29:7+02:00','2016-5-3T12:29:7+02:00',NULL,'10','Ma fille est en 5eme, elle a besoin de soutien scolaire en physique-chimie','Aider au devoirs / cours divers','11','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-14T8:47:19+02:00','2016-7-14T8:47:19+02:00',NULL,'14','Devant partir très tôt au travail le matin, je recherche une personne qui pourrais accompagner mes 2 enfants, Lucile (5 ans) et Camille (8 ans) de chez à l''école qui à 15 min à pied. Il faudrait que la personne soit chez nous à 7h45','Enmener enfants à l''école','8','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-3T17:35:25+02:00','2016-5-3T17:35:25+02:00',NULL,'67','Etant handicapé, je cherche un personne pour aller me chercher mes cigarettes au tabac','Faire une course au tabac','1','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-2T23:40:51+02:00','2016-6-2T23:40:51+02:00',NULL,'10','Absent de chez moi pendant un mois, je recherche une persenne pour regarder mon courrier et éventiellement aller chercher des colis à la poste','Regarder le courrier','3','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-9T6:9:17+02:00','2016-7-9T6:9:17+02:00',NULL,'8','Revenant du boulot trop tard le soir, je recherche une personne qui pourrait m''amener une baguette de pain à la boulangerie','Passer à la boulangerie','12','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-26T15:17:1+02:00','2016-7-26T15:17:1+02:00',NULL,'9','Habitant au 5eme etage sans ascenceur, je cherche une personne pour monter pour faire mes courses à la superette et ame remonter les course','Aller à la superette','10','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-27T16:14:23+02:00','2016-6-27T16:14:23+02:00',NULL,'41','Je voudrais apprendre à faire le Paris-Brest et le kouign-amann','Prendre cours de patisserie','12','true', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-29T23:31:34+02:00','2016-5-29T23:31:34+02:00',NULL,'53','Je recherche une personne pour m''aider à organiser les 30 ans de mon copain, j''ai besoin de conseil pour des hotel et retaurants sur Vannes','Organiser un anniversaire original','6','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-7T5:11:18+02:00','2016-7-7T5:11:18+02:00',NULL,'20','J''ai dois convoyer une grosse armoire en bois massif sur une distance de 10km, j''''aurais besoin d''un coup de main','Porter un objet volumineux','11','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-23T5:34:5+02:00','2016-7-23T5:34:5+02:00',NULL,'61','jee recherche une personne pour faire le ménage chez moi 1 fois par mois','Ménage','10','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-24T4:56:15+02:00','2016-6-24T4:56:15+02:00',NULL,'27','Je recherche quelqu''un pour repasser mes 5 chemises, une fois par semaine','Repassage de chemise','3','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-13T6:12:36+02:00','2016-6-13T6:12:36+02:00',NULL,'7','J''ai déchier mon pantalon de costume, mais je sais pas coudre, la déchirure est au niveau de l''entre-jambe , elle mesure environ 10-12 cm','Recoudre un pantalon déchiré','11','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-5T23:55:27+02:00','2016-5-5T23:55:27+02:00',NULL,'66','En tant que nouvelle trésorière néophite de mon club de sport, je souhaiterai avoir une formation/initiation en comptabilité par un expert','Comptabilité','5','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-11T19:16:9+02:00','2016-6-11T19:16:9+02:00',NULL,'52','Je vien de m''installer dans mon appart, et j''ai besoin d''un personne pour m''aider à monter l''armature de mon lit double','Monter un lit double','9','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-8T4:58:1+02:00','2016-6-8T4:58:1+02:00',NULL,'48','Je déménage 2 personne pour m''aider à déménager mon T2 ce week-end','Déménager','5','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-23T20:26:29+02:00','2016-5-23T20:26:29+02:00',NULL,'48','Pour brancher  mon nouveau four, je dois débrancher et rebrancher une prise mural, comme je crains de faire une betîse , je recherche quelqu''un qui s''y connais pour faire le branchement','Brancher un four','9','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-4T15:23:53+02:00','2016-5-4T15:23:53+02:00',NULL,'52','Comme je dois aller au mariage de ma nièce le mois prochain, je cherche une personne qui pourrait garder ma chienne pendant le week-end','Garde de chien','10','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-5T3:49:25+02:00','2016-7-5T3:49:25+02:00',NULL,'34','Je recherche un hébergement pour le week-end du 17/09 sur la ville de Fillagolles','Hebergement: maison, caravane,tente','1','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-24T8:19:27+02:00','2016-7-24T8:19:27+02:00',NULL,'57','Je m''interese à la modélisation 3D, mais asouhaiterais avoir une initiaition d''un connaisseur pour vérifier que je veux me lancer dans ce domaine','Installer logiciel de Modélisation 3D','2','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-17T1:47:22+02:00','2016-6-17T1:47:22+02:00',NULL,'60','J''ai choppé un virus sur internet, je recherche une personne capable de me dire comment le supprimer. Les données sur mon PC sont super importantes pour moi','Supprimer des virus','6','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-25T2:16:31+02:00','2016-5-25T2:16:31+02:00',NULL,'71','Je recherche une personne pour me monter comment faire le site internet de mon club de poterie','Créer un site internet','6','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-24T8:2:20+02:00','2016-5-24T8:2:20+02:00',NULL,'22','J''ai des photos de vacances, sur lequels j''ai des tâches à cause de la mauvaise qualité de mon appareil. On  m''a dit que je pouvais les reprendre en faisant une retouche photo, mais je n''ai pas d''ordinateur, ni le logiciel nécessaire pour faire ce travail.','montage photo','6','true', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-8T13:19:31+02:00','2016-6-8T13:19:31+02:00',NULL,'17','J''ai fais plusieurs videos avec mon téléphone pendant mes vacances, je chercherche une peronne capable de faire un montage vidéo de 3 min, pour faire un cadeau d''anniversiare de mariage à ma femme','montage vidéo','5','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-26T16:30:18+02:00','2016-7-26T16:30:18+02:00',NULL,'48','Ayant toujours eu des PC, je viens de m''acheter un MacBookAir, mais j''ai du mal à comprendre comment fonctionne iTunes, je voudrais télécharger des séries','télécharger des séries sur Itunes','7','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-22T4:3:24+02:00','2016-5-22T4:3:24+02:00',NULL,'28','J''ai fait tombé mon smartphone hier, j''ai acheté un écran sur le net et je recherche quelqu''un qui saurait l''installer pour réparer mon téléphone','Changer écran téléphone','12','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-10T19:49:58+02:00','2016-6-10T19:49:58+02:00',NULL,'2','j''ai reçu la nouvelle box, mais j''ai peur de faire une betise en l''installant, est ce qu''un spécialiste pourrait m''aider?','Installer une box','1','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-14T6:49:13+02:00','2016-6-14T6:49:13+02:00',NULL,'7','Qui peut m''aider à faire l''installation de mon nouveau matériel informatique svp?','Installer un PC, écran…','9','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-11T14:3:33+02:00','2016-7-11T14:3:33+02:00',NULL,'21','J''ai viens de remplir ma déclration d''impot, mais je souhaiterai avoir la validation d''un 3eme oeil afin de vérifier que j''ai bien déclarer mes travaux d''instllation de chaudière','Déclaration impôt','4','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-11T15:23:40+02:00','2016-5-11T15:23:40+02:00',NULL,'57','J''ai besoin de conseil en défiscalisation','Optimisation impôt','11','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-28T13:3:35+02:00','2016-7-28T13:3:35+02:00',NULL,'20','Cela fait 8 mois que mon appartement est en vente, mais je n''arrive pas à le vendre','Vendre bien immo','11','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-5T16:9:8+02:00','2016-5-5T16:9:8+02:00',NULL,'15','je n''arrive pas à vendre mon canapé d''angle depuis 4 mois, je ne souhaite pas le bragder, est ce quelqu''un peut me conseiller?','Vendre un canapé','5','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-1T18:18:47+02:00','2016-5-1T18:18:47+02:00',NULL,'71','Venant de ma province natale, et arrivant en Septembre sur Paris pour mes études, je souhaiterai me faire aider pour trouver un appartement sur Paris, j''ai entendu dire que c''était très compliqué','Louer un bien immo','2','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-10T13:20:36+02:00','2016-5-10T13:20:36+02:00',NULL,'16','Ma voiture commence à rendre l''âme..., je voudrais une autre, mais mon budget est limité et je n''y rien en voiture','Achat véhicule','11','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-16T12:42:28+02:00','2016-7-16T12:42:28+02:00',NULL,'67','Jeune mama célibataire et active, j''ai besoin de conseil pour acheter la meilleure poussete pour ma fille de 4 mois','Achat matériel bébé','9','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-28T22:44:33+02:00','2016-5-28T22:44:33+02:00',NULL,'41','Fan de l''Inde depuis toujours, je souhaite apprendre à cuisiner de bon plats indiens','Gastronomie indienne','5','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-21T16:20:51+02:00','2016-5-21T16:20:51+02:00',NULL,'64','Je suis backpacker, j''ai voyagé dans le monde entier, j''ai l''intention d''aller au sud du Portugal le mois prochain, je recherche quelqu''un qui pourrait me donner des bonnes adresses et bon plans sur cette région','Voyage au portugal','2','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-25T4:13:55+02:00','2016-6-25T4:13:55+02:00',NULL,'30','J''ai besoin de conseils pour décorer mon studio, car j''ai l''impression aujourd''hui qu''il ressemble un appartement des années 80','Décoration intérieur','6','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-14T20:22:22+02:00','2016-6-14T20:22:22+02:00',NULL,'60','Je souhaiterai changer d''assurance auto, notamment en prenant une assurance sur internet, mais je ne sais pas quel comparateur utiliser.','Conseil pour choisir une assurance','6','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-13T1:54:57+02:00','2016-5-13T1:54:57+02:00',NULL,'54','J''essaye de commencer un régime, et je vcoudrais assainir mon alimentation et manger de la nourriture bio. Je cherche une personne qui s''y connait en régime détox','Alimentation bio','9','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-22T16:47:56+02:00','2016-5-22T16:47:56+02:00',NULL,'64','Je viens d''acheter une piscine, j''ai entendu parler de robot netoyeur, mais je ne comprends pas comment ça marchen. Lequel choisir.. etc...','Maintenance piscine','10','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-19T9:20:37+02:00','2016-5-19T9:20:37+02:00',NULL,'42','J''ai besoin d''aide pour repeindre la chambre de mon fils qui va naître dans un mois.','Peindre les murs d''une chambre','5','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-8T10:59:45+02:00','2016-7-8T10:59:45+02:00',NULL,'12','J''ai envie d''achete un smatphone, mais je ne sais pas lequel choisir. Mais j''aurais besoin de conseil pour m''indiquer les meilleurs modèles','Conseil pour l''achat d''un smartphone','9','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-11T11:38:26+02:00','2016-6-11T11:38:26+02:00',NULL,'11','Jeune auto-entrepreneur, je recherche une personne qui pourrait vérifier mes comptes pour la déclation de fin d''année','Assistance comptabilité','8','true', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-27T21:11:22+02:00','2016-6-27T21:11:22+02:00',NULL,'60','Je voudrais porter plainte contre un artisant qui m''a arnaquer dans la réalisation de travaux, mais je ne sais pas quels sont mes recours possibles','Conseil juridique','3','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-20T3:34:48+02:00','2016-6-20T3:34:48+02:00',NULL,'24','Je possède un catamarant, et je recherche une personne pour m''accompagner pour une sortie bateau le weel-end prochain','Faire un tour de bateau','11','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-10T20:54:11+02:00','2016-5-10T20:54:11+02:00',NULL,'50','Je recherche des gens pour remplir ma voiture le matin sur le trajet de Nogent sur marne à la Défense','Proposer un déplacement (covoit)','5','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-4T5:36:14+02:00','2016-7-4T5:36:14+02:00',NULL,'20','Je recherche un animateur-musicien pour l''anniversaire de ma fille qui aura 4 ans dans 1 mois','Service d''animation - musiques','5','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-3T13:42:9+02:00','2016-7-3T13:42:9+02:00',NULL,'23','Etant nouvelle sur Paris, je recherche une personne qui s''y connaisse en Histoire del''Art pour me guider lors d''une visite au musée du Louvre','Accompagnement pour visiter le Louvre','1','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-28T11:30:46+02:00','2016-6-28T11:30:46+02:00',NULL,'7','Amateur de vin, mais qu''y n''y connais rien, J''ai toujours rêvé de m''y connaitre. ','Degustation de bons vins','6','true', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-5-29T17:35:15+02:00','2016-5-29T17:35:15+02:00',NULL,'48','Je recherche une personne possédant une ferrai pour m''enmener faire un tour','Faire un tour dans une voiture de sport','1','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-7-11T18:9:6+02:00','2016-7-11T18:9:6+02:00',NULL,'22','Je recherche des personnes pour m''accompagner le dimanche matin pour faire une sortie Vélo de Béthunes à Houlgate. La distance est de 10km','Sortie vélo','12','pending', '', '', NULL, '', NULL);
INSERT INTO "requests" ("created_at","updated_at","deleted_at","user_id","content","title","views","status", "period_start", "period_end", "frequency", "frequency_unit", "duration")
 VALUES  ('2016-6-1T6:46:56+02:00','2016-6-1T6:46:56+02:00',NULL,'52','On m''a offert un drône pour mon anniversaire, mais je ne sais pas du tout comment le piloter, je rechercha une personne qui en a déjà un qui pourrait m''apprendre à me perfectionner','apprendre à piloter un drône','6','pending', '', '', NULL, '', NULL);
